name: anlp
channels:
  - defaults
dependencies:
  - nltk=3.4
  - spacy=2.0.12
  - scikit-learn=0.20.2
  - pandas=0.24.0
  - matplotlib=3.0.2
  - gensim=3.4.0
  - pip:
    - tensorflow==1.13.0-rc2
    - keras==2.2.4

